### ISSUE TITLE
Comparison with LLMA

### ISSUE THREAD

**Issue by hemingkx** [apoorvumang/prompt-lookup-decoding#4]
Hey Apoorv,

Thanks for your awesome work! How does this code implementation differ from the idea of [LLMA](http://arxiv.org/abs/2304.04487)? Maybe comparisons should be conducted in your upcoming script.

PS: I can not find LLMA's code implementation in their released [link](https://github.com/microsoft/unilm).

**Comment by apoorvumang** [comment]
Hey Heming, yes I very recently read the LLMA paper.

Prompt lookup seems like exactly the same idea that they had - so not sure what comparisons we can make. We will definitely cite their work though

**Comment by hemingkx** [comment]
Thx for your reply! Looking forward to your manuscript. I have smoothly run your implementation and added the results to our comparative experiment. Nice work!
