### ISSUE TITLE
AttributeError: 'MistralForCausalLM' object has no attribute '_extend_attention_mask'

### ISSUE THREAD

**Issue by allenlu2009** [apoorvumang/prompt-lookup-decoding#7]
AttributeError: 'MistralForCausalLM' object has no attribute '_extend_attention_mask'

_Originally posted by @riyaj8888 in https://github.com/apoorvumang/prompt-lookup-decoding/issues/2#issuecomment-1905394884_

I encountered the same error.

**Comment by allenlu2009** [comment]
Hi Apoorvumang,

Thank you for your message!

I am using the Colab (T4 GPU) to run your colab example directly.  The
transformer version is 4.42.4.

Thanks and regards，

Allen



Please find the log of running colab below:
================================================== Requirement already
satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.42.4)
Collecting optimum Downloading optimum-1.21.4-py3-none-any.whl.metadata (19
kB) Requirement already satisfied: filelock in
/usr/local/lib/python3.10/dist-packages (from transformers) (3.15.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in
/usr/local/lib/python3.10/dist-packages (from transformers) (0.23.5)
Requirement already satisfied: numpy<2.0,>=1.17 in
/usr/local/lib/python3.10/dist-packages (from transformers) (1.25.2)
Requirement already satisfied: packaging>=20.0 in
/usr/local/lib/python3.10/dist-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in
/usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in
/usr/local/lib/python3.10/dist-packages (from transformers) (2024.5.15)
Requirement already satisfied: requests in
/usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Requirement already satisfied: safetensors>=0.4.1 in
/usr/local/lib/python3.10/dist-packages (from transformers) (0.4.3)
Requirement already satisfied: tokenizers<0.20,>=0.19 in
/usr/local/lib/python3.10/dist-packages (from transformers) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in
/usr/local/lib/python3.10/dist-packages (from transformers) (4.66.4)
Collecting coloredlogs (from optimum) Downloading
coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB) Requirement
already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from
optimum) (1.13.1) Requirement already satisfied: torch>=1.11 in
/usr/local/lib/python3.10/dist-packages (from optimum) (2.3.1+cu121)
Collecting datasets (from optimum) Downloading
datasets-2.21.0-py3-none-any.whl.metadata (21 kB) Requirement already
satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages
(from huggingface-hub<1.0,>=0.23.2->transformers) (2023.6.0) Requirement
already satisfied: typing-extensions>=3.7.4.3 in
/usr/local/lib/python3.10/dist-packages (from
huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2) Requirement already
satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from
torch>=1.11->optimum) (3.3) Requirement already satisfied: jinja2 in
/usr/local/lib/python3.10/dist-packages (from torch>=1.11->optimum) (3.1.4)
=================================================

The error message:

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-8-0ccc7601f5d3> <https://localhost:8080/#> in <cell
line: 13>()     17
return_dict_in_generate=True)     18 else:
---> 19     out = model.greedy_search_pld(inputs.input_ids,     20
                          attention_mask = inputs.attention_mask,
21
stopping_criteria=StoppingCriteriaList([MaxLengthCriteria(max_length=len(inputs.input_ids[0])
+ max_new_tokens)]),


------------------------------
2 frames
------------------------------

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py
<https://localhost:8080/#> in __getattr__(self, name)   1707
  if name in modules:   1708                 return modules[name]
-> 1709         raise AttributeError(f"'{type(self).__name__}' object
has no attribute '{name}'")   1710    1711     def __setattr__(self,
name: str, value: Union[Tensor, 'Module']) -> None:


AttributeError: 'MistralForCausalLM' object has no attribute
'_extend_attention_mask'

**Comment by allenlu2009** [comment]
I also ran the demo-pld.ipynb in Colab using L4 GPU and got the same error message. 

Please let me know if you any other message.

Allen

>---------------------------------------------------------------------------
import transformers
print(transformers.__version__)
> 4.42.4

model_name = "mistralai/Mistral-7B-Instruct-v0.1"


AttributeError                            Traceback (most recent call last)
[<ipython-input-10-916db4f5eab4>](https://localhost:8080/#) in <cell line: 13>()
     16                          return_dict_in_generate=True)
     17 else:
---> 18     out = model.greedy_search_pld(inputs.input_ids, 
     19                               attention_mask = inputs.attention_mask,
     20                               stopping_criteria=StoppingCriteriaList([MaxLengthCriteria(max_length=len(inputs.input_ids[0]) + max_new_tokens)]),

2 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1707             if name in modules:
   1708                 return modules[name]
-> 1709         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
   1710 
   1711     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'MistralForCausalLM' object has no attribute '_extend_attention_mask'

**Comment by apoorvumang** [comment]
It seems a lot of stuff has changed in the transformers/mistral API since I made the notebook. eg. `_extend_attention_mask` is no longer there, but there's a new `prepare_attention_mask` https://github.com/huggingface/transformers/blob/main/src/transformers/generation/candidate_generator.py#L412

Might take some work to rework this. I have tried to fix the colab but I don't think its working fast rn (probably due to other changes)

Could you pls elaborate why you want to run PLD this way instead of just using it in transformers? Might give me motivation to try and fix stuff 😅

**Comment by allenlu2009** [comment]
Thanks for the information! I used the **prompt_lookup_num_tokens** option in `generate` to achieve speedup, which was helpful. However, I've noticed varying speedups across different scenarios, like summarization and chat. I'd like to dive deeper to understand why this happens and explore ways to improve it.

**Comment by allenlu2009** [comment]
> It seems a lot of stuff has changed in the transformers/mistral API since I made the notebook. eg. `_extend_attention_mask` is no longer there, but there's a new `prepare_attention_mask` https://github.com/huggingface/transformers/blob/main/src/transformers/generation/candidate_generator.py#L412
> 
> Might take some work to rework this. I have tried to fix the colab but I don't think its working fast rn (probably due to other changes)
> 
> Could you pls elaborate why you want to run PLD this way instead of just using it in transformers? Might give me motivation to try and fix stuff 😅

Your fix of changing `_extend_attention_mask` to `prepare_attention_mask` actually works, but in an unexpected way. The results are shown in the table below. In summary, the fix works on Colab L4 GPU and RTX 3060, but not on Colab T4 GPU. I'm not sure why, but it seems to align with your observation of 10 tokens/sec. Thanks for the fix!

| GPU             | `use_new_generate = True` | `use_new_generate = False`, baseline |
|-----------------|---------------------------|----------------------------|
| Colab GPU T4     | 11 tokens/sec             | 15 tokens/sec              |
| Colab GPU L4     | 32 tokens/sec             | 15 tokens/sec              |
| Desktop RTX3060 | 24 tokens/sec             | 13 tokens/sec              |

**Comment by allenlu2009** [comment]
Closes #7

**Comment by apoorvumang** [comment]
Oh wow, thank you so much for testing @allenlu2009 !

I suspect that reimplementing the notebook with the latest transformers API (using the `CandidateGenerator` class, using the new cache implementation etc) should make it faster. If anyone wants to rewrite the notebook with that I would be really grateful :)

**Comment by allenlu2009** [comment]
Per your suggestion, I tried to revise your code using the CandidateGenerator class with the cache (I am not sure if this is the new cache implementation) and compare with your original code, and the transformers model.generate with prompt_lookup_num_tokens option.   The results are shown below.

Some observations and issues:
* Transformer prompt_lookup_num_tokens shows the best speed-up across different GPUs.
* There is negligible difference between your original code and my revised version using the CandidateGenerator class. There might be something wrong. I would appreciate it if you could take some time to check it. :)
* The Colab GPU T4 seems to behave strangely with both the original and revised versions, but it behaves normally in the Transformer prompt_lookup_num_tokens version. I'm not sure why.

**Comment by allenlu2009** [comment]
| GPU      | use_new_generate | orig: greedy_search_pld | Speed up | candidate generator | Speed up | Transformer prompt_lookup_num_tokens | Speed up |
|----------|------------------|-------------------------|----------|---------------------|----------|--------------------------------------|----------|
| L4       | TRUE             | 33.9                    | 2.2      | 33.6                | 2.2      | 33.6                                 | 2.3      |
| L4       | FALSE            | 15.2                    |          | 15.2                |          | 14.3                                 |          |
| T4       | TRUE             | 11.1                    | 0.7      | 14.3                | 1.0      | 33.2                                 | 2.2      |
| T4       | FALSE            | 15.6                    |          | 14.6                |          | 14.9                                 |          |
| RTX3060  | TRUE             | 24.7                    | 2.0      | 26.4                | 2.0      | 31.8                                 | 2.5      |
| RTX3060  | FALSE            | 12.4                    |          | 13.2                |          | 12.8                                 |          |

**Comment by allenlu2009** [comment]
Please find the jupyter files attached.

**Comment by allenlu2009** [comment]
[candidate_generator_upload.ipynb.zip](https://github.com/user-attachments/files/16887226/candidate_generator_upload.ipynb.zip)
[transformers_pld_upload.ipynb.zip](https://github.com/user-attachments/files/16887232/transformers_pld_upload.ipynb.zip)
